FROM ubuntu:20.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libopenbabel-dev \
    librdkit1v5 \
    librdkit-dev \
    python3-numpy \
    python3-scipy \
    python3-sklearn \
    python3-joblib \
    python3-pandas

# Install ODDT
RUN pip3 install oddt

# Set the working directory
WORKDIR /app